trigger:
- main  # Simple and sufficient for most cases

pool:
  vmImage: ubuntu-latest

steps:
  # Install Node.js
  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'
    displayName: Install Node.js

  # Install dependencies and build
  - script: |
      npm install
      npm run build
    displayName: npm install and build

  # Run code linting (optional, for code quality checks)
  - script: |
      npm run lint
    displayName: Run Linter

  # Run tests (optional, based on your project setup)
  - script: |
      npm test
    displayName: Run Unit Tests

  # Copy necessary files (including hidden files) to Artifact Staging Directory
  - script: |
      mkdir -p $(Build.ArtifactStagingDirectory)
      cp -R . $(Build.ArtifactStagingDirectory)
    displayName: Copy files to Artifact Staging Directory

  # Publish build artifacts
  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: $(Build.ArtifactStagingDirectory)
      artifactName: 'drop' #artifact name change to as per requirement
      publishLocation: 'Container'
    displayName: Publish Build Artifacts
