# Azure DevOps Pipeline YAML
# Replace 'your-project-name' with your actual project name

trigger:
  branches:
    include:
      - main
pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'
    displayName: Install Node.js

  - script: |
      npm install
      npm run build
    displayName: npm install and build

  - script: |
      npm run lint
    displayName: Run Linter

  - script: |
      npm test
    displayName: Run Unit Tests

  - script: |
      mkdir -p $(Build.ArtifactStagingDirectory)
      cp -R . $(Build.ArtifactStagingDirectory)
    displayName: Copy files to Artifact Staging Directory

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: $(Build.ArtifactStagingDirectory)
      artifactName: 'drop'
      publishLocation: 'Container'
    displayName: Publish Build Artifacts